### PR TITLE
Clean Asp.Net core API

### PR DESCRIPTION
**Pull request by wallymathieu**
Since OWIN is not used anymore, using clean asp.net core

### CODE REVIEW

**Comment by wallymathieu** [comment]
Could be improved by adopting some extensions from https://www.strathweb.com/2017/01/building-microservices-with-asp-net-core-without-mvc/

**Comment by wastaz** [comment]
If this is an example of a clean asp.net core version then maybe dont use the Microsoft.AspNetCore.All package since it brings in everything and the kitchen sink and the elephant as well? (I mean, it even drags in flippin entity framework).

**Comment by wallymathieu** [comment]
I agree. I've mostly focused on porting the OWIN-sample.

**Comment by wallymathieu** [comment]
I'm at work right now, but perhaps you could offer a better selection of NuGet packages so that I can merge this PR. 

Also note that these API's all implement an XML API in order to show how to implement same API in many different approaches. We should submit a ToDo Mvc Backend project as well in order to showcase a JSON API.

**Pull request merged**
